name: Deny

on:
  push:
    branches:
      - master
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  pull_request:
    branches:
      - master
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  cargo-deny:
    name: cargo deny
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          fetch-depth: 1

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.12
        with:
          command: check
          log-level: warn
