name: Deny

on:
  push:
    branches:
      - master
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  pull_request:
    branches:
      - master
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  cargo-deny:
    name: cargo deny
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@e2f4ede4a4e60ea15ff31bc0647485d80c66cfba # v2.0.12
        with:
          command: check
          log-level: warn
